### DISCUSSION TITLE
Setting up Growstuff plantings as Home Assistant Sensors [WIP]

### DISCUSSION THREAD

**Discussion by CloCkWeRX** [Growstuff/growstuff#2746] [Show and tell]
[Home Assistant](https://www.home-assistant.io/) is a home automation platform that supports a range of sensors and triggers.

My use case is to display the progress of my plantings in the home assistant dashboard.

Home assistant supports a generic rest integration:
https://www.home-assistant.io/integrations/rest/

```
  - platform: rest
    name: Growstuff Plantings
    resource: https://www.growstuff.org/members/clockwerx/plantings.json
    value_template: '{{ value_json.crop_name }}'
    json_attributes:
      - crop_name
      - finish_predicted_at
      - percentage_grown
      - thumbnail_url
      - active
      - slug
  - platform: template
    sensors:
       crop_percentage:
        friendly_name_template: '{{ states.sensor.growstuff_plantings.attributes["crop_name"] }} Percentage'
        value_template: '{{ states.sensor.growstuff_plantings.attributes["percentage_grown"] }}'
        entity_picture_template: '{{ states.sensor.growstuff_plantings.attributes["thumbnail_url"] }}'
        attribute_templates:
          finish_predicted_at: '{{ states.sensor.growstuff_plantings.attributes["finish_predicted_at"] }}'
          slug: 'https://www.growstuff.org/plantings/{{ states.sensor.growstuff_plantings.attributes["slug"] }}'

```

Note: I tried using the API, but got errors
```
curl -X GET "https://www.growstuff.org/api/v1/plantings?filter%5Bowner%5D=clockwerx" -H "accept: application/vnd.api+json"
```

This will get your first crop and show the attributes:
![image](https://user-images.githubusercontent.com/365751/105624183-9b9bec80-5e6f-11eb-8400-e7e877d9d4c1.png)

Remaining tasks
- [ ] Multiple crops without repeating sensors - rewrite as custom component?
